#!/usr/bin/env python3
"""Export papers/ briefs to the website's data/research.yaml.

Walks papers/<year>/*.md, extracts title / date / gist / links per brief,
and writes a deterministic YAML digest (newest first). A brief missing any
field is skipped with a warning; it must never block the digest.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

BLOB_BASE = "https://github.com/Flechsen/ML_Trend_Researcher/blob/master/papers"

HEADER = (
    "# GENERATED FILE — regenerated by ML_Trend_Researcher's weekly workflow\n"
    "# (scripts/export_website_digest.py). Do not edit by hand.\n"
)

# Sentence ends at ./!/? followed by whitespace + a capital/digit/quote/paren.
# Lookbehinds keep common abbreviations (e.g., i.e., etc., vs., cf., et al.)
# from terminating the sentence early.
_SENTENCE_END = re.compile(
    r"(?<!\be\.g)(?<!\bi\.e)(?<!\betc)(?<!\bvs)(?<!\bcf)(?<!\bal)"
    r"[.!?](?=\s+[A-Z0-9(\"'])"
    r"|[.!?]$"
)
_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def first_sentence(text: str) -> str | None:
    text = " ".join(text.split())
    if not text:
        return None
    m = _SENTENCE_END.search(text)
    return text[: m.end()] if m else text


def _section(body: str, heading: str) -> str | None:
    m = re.search(
        rf"^## {re.escape(heading)}\s*$(.*?)(?=^## |\Z)",
        body,
        re.MULTILINE | re.DOTALL,
    )
    return m.group(1).strip() if m else None


def _meta(body: str, key: str) -> str | None:
    m = re.search(rf"^- {re.escape(key)}:\s*(.+)$", body, re.MULTILINE)
    return m.group(1).strip() if m else None


def parse_brief(path: Path, papers_dir: Path) -> dict | None:
    body = path.read_text(encoding="utf-8")
    title_m = re.search(r"^# (.+)$", body, re.MULTILINE)
    date = _meta(body, "Published")
    why = _section(body, "Why this matters")
    entry = {
        "title": title_m.group(1).strip() if title_m else None,
        "date": date if date and _DATE.match(date) else None,
        "gist": first_sentence(why) if why else None,
        "arxiv": _meta(body, "arXiv link"),
        "brief": f"{BLOB_BASE}/{path.relative_to(papers_dir).as_posix()}",
    }
    missing = [k for k, v in entry.items() if not v]
    if missing:
        print(f"skipping {path}: missing {', '.join(missing)}", file=sys.stderr)
        return None
    return entry


def export(papers_dir: Path, out: Path) -> int:
    entries = [
        e
        for p in sorted(papers_dir.glob("*/*.md"))
        if p.name != "INDEX.md" and (e := parse_brief(p, papers_dir))
    ]
    entries.sort(key=lambda e: (e["date"], e["brief"]), reverse=True)
    body = yaml.safe_dump(entries, sort_keys=False, allow_unicode=True, width=88)
    out.write_text(HEADER + body, encoding="utf-8")
    return len(entries)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--papers-dir", type=Path, default=Path("papers"))
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    n = export(args.papers_dir, args.out)
    print(f"exported {n} entries to {args.out}")


if __name__ == "__main__":
    main()
